name: nutri_leche
description: Portal de Empleados Nutri Leche Ecuador
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ðŸ“… Calendario
  table_calendar: ^3.1.2

  # ðŸ“± Utilidades generales
  uuid: ^4.5.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2

  # ðŸŒŽ InternacionalizaciÃ³n
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

  # ðŸ“‚ Archivos y multimedia
  path_provider: ^2.1.4
  file_picker: ^10.3.3
  image_picker: ^1.1.2

  # ðŸ“„ PDF y herramientas
  pdf: ^3.11.0
  printing: ^5.12.0
  universal_html: ^2.2.4
  mime: ^2.0.0

  # ðŸ“¦ Firebase (comentado, sin usar en este proyecto)
  # firebase_core: ^3.15.2
  # cloud_firestore: ^5.6.12
  # firebase_messaging: ^15.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  # ðŸ–¼ï¸ Activos
  assets:
    - assets/icono/nutrileche.png
