name: nutri_leche
description: Portal de Empleados Nutri Leche Ecuador
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ðŸ“… Calendario de eventos
  table_calendar: ^3.1.2

  # ðŸ“± Utilidades generales
  uuid: ^4.5.1
  provider: ^6.1.2
  shared_preferences: ^2.3.3

  # ðŸŒŽ InternacionalizaciÃ³n y fechas
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

  # ðŸ“‚ Archivos, documentos y multimedia
  path_provider: ^2.1.5
  file_picker: ^8.1.4
  image_picker: ^1.1.2
  open_filex: ^4.7.0
  mime: ^2.0.0
  universal_html: ^2.2.4

  # ðŸ“„ PDF y herramientas de impresiÃ³n
  pdf: ^3.11.0
  printing: ^5.12.0
  flutter_pdfview: ^1.4.3

  # ðŸŒ NavegaciÃ³n a enlaces externos (visor web)
  url_launcher: ^6.3.1

  # ðŸ“¦ Firebase (opcional, sin uso actual)
  # firebase_core: ^3.15.2
  # cloud_firestore: ^5.6.12
  # firebase_messaging: ^15.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  # ðŸ–¼ï¸ Activos de la aplicaciÃ³n
  assets:
    - assets/icono/nutrileche.png
